team_subs = {
        'Orioles':'/r/orioles',
        'Yankees':'/r/NYYankees',
        'Red Sox':'/r/redsox',
        'Blue Jays':'/r/TorontoBlueJays',
        'Rays':'/r/TampaBayRays',
        'Twins':'/r/minnesotatwins',
        'Guardians':'/r/ClevelandGuardians',
        'Royals':'/r/KCRoyals/',
        'Tigers':'/r/motorcitykitties',
        'White Sox':'/r/whitesox',
        'Rangers':'/r/TexasRangers',
        'Mariners':'/r/Mariners',
        'Athletics':'/r/OaklandAthletics',
        'Astros':'/r/Astros',
        'Angels':'/r/AngelsBaseball',
        'D-backs':'/r/azdiamondbacks',
        'Cubs':'/r/chicubs',
        'Braves':'/r/Braves',
        'Rockies':'/r/ColoradoRockies',
        'Reds':'/r/reds',
        'Marlins':'/r/MiamiMarlins',
        'Dodgers':'/r/dodgers',
        'Brewers':'/r/brewers',
        'Mets':'/r/NewYorkMets',
        'Padres':'/r/padres',
        'Pirates':'/r/buccos',
        'Phillies':'/r/phillies',
        'Giants':'/r/SFGiants',
        'Cardinals':'/r/cardinals',
        'Nationals':'/r/nationals'
}

team_selection = {
       'Orioles': ['BAL', 'Os', "O's", 'Orioles'],
        'Yankees':['NYY', 'Yanks', 'yankees'],
        'Red Sox':['BOS', 'bosox', 'red socks', 'red sox'],
        'Blue Jays':['TOR', 'jays', 'Blue Jays'],
        'Rays':['TBR', 'rays', 'TB'],
        'Twins':['MIN', 'twins'],
        'Guardians':['CLE', 'guardians'],
        'Royals':['KCR', 'royals', 'KC'],
        'Tigers':['DET', 'tigers'],
        'White Sox':['CWS', 'white sox'],
        'Rangers':['TEX', 'rangers'],
        'Mariners':['SEA', 'mariners'],
        'Athletics':['OAK', 'athletics'],
        'Astros':['HOU', 'astros', 'stros'],
        'Angels':['LAA', 'angels'],
        'D-backs':['ARI', 'AZ', 'dbacks', 'diamondbacks'],
        'Cubs':['CHC', 'CUBS', 'chicago'],
        'Braves':['ATL', 'braves'],
        'Rockies':['COL', 'CO', 'rockies'],
        'Reds':['CIN', 'reds'],
        'Marlins':['MIA', 'marlins'],
        'Dodgers':['LAD', 'dodgers'],
        'Brewers':['MIL', 'brewers'],
        'Mets':['NYM', 'mets'],
        'Padres':['SDP', 'padres', 'dads'],
        'Pirates':['PIT', 'pirates'],
        'Phillies':['PHI', 'phillies', 'philly'],
        'Giants':['SFG', 'giants'],
        'Cardinals':['STL', 'cardinals'],
        'Nationals':['WSH', 'nats', 'nationals']
}